---
title: "Inductive"
output:
  html_document:
    toc: TRUE
    toc_float: true
    theme: cosmo
header-includes:
- \usepackage{amsmath}
- \usepackage[makeroom]{cancel}
---

```{r global_options, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = F, warning = F, cache = F, message = F,
                      sanitiz = F, fig.width = 5, fig.height = 3)
```


# Inductive

Participants choose how much they endorse "An X that costs $\varepsilon$ less than an expensive X is expensive."

## Inspect joint distribution

Directly inspecting the joint posterior distribution for "expensive", we take the expectation over $L_1(x, \theta)$ of $x-\varepsilon > \theta$.

That is,

$S_1(\mbox{still expensive}) = \int_{x,\theta} L_1(x,\theta|\mbox{x is expensive})
\left.\begin{cases} 1 & x-\varepsilon > \theta \\ 0 & \mbox{otherwise}\end{cases}\right\}dxd\theta$

## Speaker model given "expensive"

Here's a way to think about this with a speaker model:

1. Participants know of an X that is expensive. They infer a price $x$ and threshold $\theta$ from this statement.
2. Participants imagine a listener who knows $\theta$ but not $x$.
3. Participants decided whether to tell this listener $x - \varepsilon > \theta$ or stay silent.

### Step 1

Participants are modeled by a listener model to get a joint distribution over $x$ and $\theta$, e.g. $L_1(x, \theta)$. We will take the expectation of responses over this distribution to get the average response.

### Step 2

Here's how the listener will interpret the two utterances:

$\begin{align}L_0(x | \mbox{still expensive}, \theta) &=
\frac{Pr(x)\delta_{x - \varepsilon > \theta}}{\int_\theta Pr(x)\delta_{x - \varepsilon > \theta} d\theta} \\ &=
\begin{cases}\frac{Pr(x)}{1 - {CDF}(\theta + \varepsilon)} & x - \varepsilon > \theta \\ 0 & \mbox{otherwise}\end{cases}\end{align}$

$L_0(x | \mbox{silent}, \theta) = Pr(x)$

### Step 3

If the utterances are equally costly, the speaker endorsements are:

$\begin{align}
S_1(u|x, \theta) &= \frac{\exp(\lambda\ln(L_0(x|u, \theta)) - c(u))}{\sum_{u'} \exp(\lambda\ln(L_0(x|u', \theta))-c(u'))} \\ &= \frac{L_0(x|u, \theta)}{\sum_{u'} L_0(x|u', \theta)}
\end{align}$

So for the "still expensive" utterance:

$\begin{align}
S_1(\mbox{still expensive}|x, \theta) &=
\frac{L_0(x|\mbox{still expensive}, \theta)}
{L_0(x|\mbox{still expensive}, \theta) + L_0(x|\mbox{silent}, \theta)} \\
&= \begin{cases}
\frac{\frac{Pr(x)}{1 - {CDF}(\theta + \varepsilon)}}
{\frac{Pr(x)}{1 - {CDF}(\theta + \varepsilon)} + Pr(x)} & x - \varepsilon > \theta \\ 0 & \mbox{otherwise}\end{cases} \\
&= \begin{cases}\frac{1}{2 - {CDF}(\theta + \varepsilon)} & x - \varepsilon > \theta \\ 0 & \mbox{otherwise}\end{cases}
\end{align}$

### Final value

When we take the expectation over $L_1$, we get:

$S_1(\mbox{still expensive}) = \int_{x,\theta} L_1(x,\theta|\mbox{x is expensive})
\left.\begin{cases}\frac{1}{2 - {CDF}(\theta + \varepsilon)} & x - \varepsilon > \theta \\ 0 & \mbox{otherwise}\end{cases}\right\}dxd\theta$

Since the $S_1(\mbox{still expensive}|x, \theta)$ value is always between $1/2$ and $1$ whenever $x-\varepsilon > \theta$, this is very similar to the "Inspect joint posterior" version.
