---
title: "Sorites Model Results: Inductive Premise"
author: "Erin Bennett"
header-includes:
   - \usepackage{tikz}
   - \usetikzlibrary{bayesnet}
output: html_document
---

```{r global_options, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = F, warning = F, cache = F, message = F,
                      sanitiz = F, fig.width = 5, fig.height = 3)
```

**Inspect joint posterior (original inductive premise model):** Expectation of $x - \varepsilon > \theta$ over joint posterior distribution of $x$ and $\theta$.

**Posterior becomes prior:** First get a distribution over prices \$$x$ for "an expensive watch" $X$:

$\$x \sim L0/L1(\mbox{"X is an expensive watch"})$

Then shift this distribution down $\varepsilon$ to get a distribution over prices $\$y$ for "a watch that costs $\$\varepsilon$ less than an expensive watch" $Y$:

$\$x ~ L0/L1(\mbox{"X is an expensive watch"})$

$\$y = \$x - \$\varepsilon$

Using this new distribution over $\$y$ as the "prior" over prices, calculate $S1(\mbox{"Y is expensive"})$.

Uhhhhh.... Wait, S1 needs to know the price. I don't think this works.

**Dist QUD:** Maybe the QUD is the parameters of the prior distribution.

The indutive premise says that:

- $x$ is the price of an object of kind $X$
- $x > \theta$
- $x - \varepsilon > \theta$

The middle claim is implied by the last one. So we can say that the speaker is trying to communicate the parameters of the price distribution of $X$ by saying that $x - \varepsilon > \theta$.

$L0(\mu, \sigma | \mbox{"...inductive..."}) \propto P(\mu)P(\sigma)P(\mbox{"...inductive..."}|\mu, \sigma)$

$\begin{align}
  P(\mbox{"...inductive..."}|\mu, \sigma) &= \int_\theta P(x > \theta + \varepsilon |\mu, \sigma)p(\theta) d\theta \\
  &=\int_\theta [1 - \Phi(\theta + \varepsilon)] p(\theta) d\theta \\
  &= 1 - \frac{1}{b-a}[\Phi(b + \varepsilon) - \Phi(a + \varepsilon)]
\end{align}$
